### ISSUE TITLE
[Rails] Pluralize i18n

### ISSUE THREAD

**Issue by StanGC** [StanGC/StanGC.github.io#124]
rails i18n 如遇到單複數的情況可以這樣寫

```
en:
  notification:
    one: You have 1 notification
    other: You have %{count} notifications
```

在指定的 key 下增加 `one`、`other` 兩個 key，並將數量帶入 other

`<%= t("notification", count: current_user.notifications.count) %>`

i18n 就會自動判斷單複數做對應的顯示

Ref:

* [Pluralizing I18n Translations in Your Rails Application](https://thoughtbot.com/blog/pluralizing-rails-i18n-translations)
