### ISSUE TITLE
[Rails] config.x 自定義 configuration

### ISSUE THREAD

**Issue by StanGC** [StanGC/StanGC.github.io#64]
Rails 4.2 後 , 可以使用 config.x 自定義一些配置

[官方範例](https://guides.rubyonrails.org/configuring.html#custom-configuration)

搭配 [config_for](https://github.com/StanGC/StanGC.github.io/issues/62) 範例
application.yml 設定如下
```
# config/application.yml
default: &DEFAULT
  first: "hello"
  second: "world"

development:
  <<: *DEFAULT

production:
  <<: *DEFAULT

```

![2018-08-21 00 27 40](https://user-images.githubusercontent.com/16208601/44353900-f2e94600-a4da-11e8-985f-5ea9ec7a2551.png)
